version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  bookservice:
    build: ./BookService
    ports:
      - "8081:8080"
    depends_on:
      - redis
  
  authorservice:
    build: ./AuthorService
    ports:
      - "8082:8080"
    depends_on:
      - redis

  categoryservice:
    build: ./CategoryService
    ports:
      - "8083:8080"
    depends_on:
      - redis
    
  userservice:
    build: ./UserService
    ports:
      - "8084:8080"
    depends_on:
      - redis
