version: '3.8'

volumes:
  postgres_data:

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: library_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bookservice:
    build: ./BookService
    ports:
      - "8081:8080"
    depends_on:
      - redis
      - postgres
    environment:
      GRPC_USER_SERVICE_GRPC_ADDRESS: "userservice:50051"
      DATABASE_URL: "postgres://postgres:root@postgres:5432/library_management"

  authorservice:
    build: ./AuthorService
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - postgres
    environment:
      GRPC_USER_SERVICE_GRPC_ADDRESS: "userservice:50051"
      DATABASE_URL: "postgres://postgres:root@postgres:5432/library_management"

  categoryservice:
    build: ./CategoryService
    ports:
      - "8083:8080"
    depends_on:
      - redis
      - postgres
    environment:
      GRPC_USER_SERVICE_GRPC_ADDRESS: "userservice:50051"
      DATABASE_URL: "postgres://postgres:root@postgres:5432/library_management"

  userservice:
    build: ./UserService
    ports:
      - "8084:8080"
      - "50051:50051"
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: "postgres://postgres:root@postgres:5432/auth_database"
